#!/bin/sh

bspc config border_width        2
bspc config window_gap         12 

bspc monitor DVI-I-1 -d I II chat debug V 
bspc monitor DVI-D-0 -d VI web mail proggn X 

bspc config top_padding 15

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config initial_polarity second_child


# Rules
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Firefox desktop=^7
bspc rule -a Gajim desktop=^3
bspc rule -a Thunderbird desktop=^8

~/.config/bspwm/panel/panel &
